import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JSeparator;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;

/**
 *
 * @author frojas
 */
public class ClienteGUI extends javax.swing.JFrame {
    private Funcion funcion;
    private int numeroDeFila;
    private int[] numerosDeAsientos;
    /**
     * Creates new form ClienteGUI
     */
    public ClienteGUI(Funcion funcion, int numeroDeFila, int[] numerosDeAsientos) {
        this.funcion = funcion;
        this.numeroDeFila = numeroDeFila;
        this.numerosDeAsientos = numerosDeAsientos;
        initComponents();
    }

    /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jlNombre = new JLabel();
        jtfNombre = new JTextField();
        jlEmail = new JLabel();
        jtfEmail = new JTextField();
        jlCelular = new JLabel();
        jtfTelefono = new JTextField();
        jSeparator1 = new JSeparator();
        jbGuardar = new JButton();
        jbOtro = new JButton();
        jbCancelar = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        jlNombre.setText("Nombre");
        jlEmail.setText("e-mail");
        jlCelular.setText("Celular");

        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent evt) {
                    jbGuardarActionPerformed(evt);
                }
            });

        jbOtro.setText("Otro...");
        jbOtro.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent evt) {
                    jbOtroActionPerformed(evt);
                }
            });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent evt) {
                    jbCancelarActionPerformed(evt);
                }
            });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addComponent(jlEmail)
                            .addComponent(jlNombre))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jtfEmail)
                            .addComponent(jtfNombre)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(jbOtro)
                        .addGap(18, 18, 18)
                        .addComponent(jbCancelar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addComponent(jlCelular))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jtfTelefono))))
                .addContainerGap())
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombre)
                    .addComponent(jtfNombre, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEmail)
                    .addComponent(jtfEmail, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCelular)
                    .addComponent(jtfTelefono, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jbGuardar)
                    .addComponent(jbOtro)
                    .addComponent(jbCancelar))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        
        setVisible(true);
        pack();
    }// </editor-fold>                        

    private void jbCancelarActionPerformed(ActionEvent evt) {                                        
        this.dispose();
    }                                       

    private void jbOtroActionPerformed(ActionEvent evt) {                                          
        this.dispose();
    }                                         

    private void jbGuardarActionPerformed(ActionEvent evt) {        
        Cliente cliente = new Cliente(jtfNombre.getText(), jtfTelefono.getText());
        Fabrica.fabricaEscenario();
        SistemaDeReserva sistemaD1 = Fabrica.getSistemaDeReserva();
        sistemaD1.reservaAsientos(funcion, numeroDeFila, numerosDeAsientos, cliente);
        
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//         java.awt.EventQueue.invokeLater(new Runnable() {
//                 public void run() {
//                     new ClienteGUI().setVisible(true);
//                 }
//             });
    }

    // Variables declaration - do not modify                     
    private JSeparator jSeparator1;
    private JButton jbGuardar;
    private JButton jbOtro;
    private JButton jbCancelar;
    private JLabel jlCelular;
    private JLabel jlEmail;
    private JLabel jlNombre;
    private JTextField jtfTelefono;
    private JTextField jtfEmail;
    private JTextField jtfNombre;
    // End of variables declaration                   
}
