import java.awt.Container;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JSeparator;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;
import javax.swing.JTextArea;
import javax.swing.JPanel;
/**
 *
 * @author frojas
 */
public class ClienteGUI extends javax.swing.JFrame {
    private Funcion funcion;
    private int numeroDeFila;
    private int[] numerosDeAsientos;
    /**
     * Creates new form ClienteGUI
     */
    public ClienteGUI(Funcion funcion, int numeroDeFila, int[] numerosDeAsientos) {
        this.funcion = funcion;
        this.numeroDeFila = numeroDeFila;
        this.numerosDeAsientos = numerosDeAsientos;
        initComponents();
    }

    /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        Container contenido = getContentPane();
        jlNombre = new JLabel();
        jlNombre.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18));        
        jtfNombre = new JTextField("                        ");
        jtfNombre.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18));        
        jlTelefono = new JLabel();
        jlTelefono.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18));        
        jtfTelefono = new JTextField("                        ");
        jtfTelefono.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18));        
        jlEmail = new JLabel();
        jlEmail.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18));        
        jtfEmail = new JTextField("                        ");
        jtfEmail.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18));        
        jbGuardar = new JButton();
        jbGuardar.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18));        
        jbOtro = new JButton();
        jbOtro.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18));        
        jbCancelar = new JButton();
        jbCancelar.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18));        
        jpDatos = new JPanel();
        jpControles = new JPanel();

        jtaFuncion = new JTextArea("FUNCION\n"+ funcion.getDetalles());
        jtaFuncion.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18));
        jtaFuncion.setEditable(false);
        jtaFuncion.setVisible(true);

        jpDatos.add(jlNombre);
        jpDatos.add(jtfNombre);
        jpDatos.add(jlTelefono);
        jpDatos.add(jtfTelefono);
        jpDatos.add(jlEmail);
        jpDatos.add(jtfEmail);
        
        jpControles.add(jbGuardar);
        jpControles.add(jbOtro);
        jpControles.add(jbCancelar);        
//         setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        jlNombre.setText("Nombre");
        jlEmail.setText("e-mail");
        jlTelefono.setText("Celular");

        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent evt) {
                    jbGuardarActionPerformed(evt);
                }
            });

        jbOtro.setText("Otro...");
        jbOtro.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent evt) {
                    jbOtroActionPerformed(evt);
                }
            });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent evt) {
                    jbCancelarActionPerformed(evt);
                }
            });
            
        contenido.add(jtaFuncion, BorderLayout.NORTH);
        contenido.add(jpDatos, BorderLayout.CENTER);
        contenido.add(jpControles, BorderLayout.SOUTH);   

        setLocation( 100, 200 );
        setSize( 200, 300 );        
        setVisible(true);
        pack();
    }// </editor-fold>                        

    private void jbCancelarActionPerformed(ActionEvent evt) {                                        
        this.dispose();
    }                                       

    private void jbOtroActionPerformed(ActionEvent evt) {                                          
        this.dispose();
    }                                         

    private void jbGuardarActionPerformed(ActionEvent evt) {        
        Cliente cliente = new Cliente(jtfNombre.getText(), jtfTelefono.getText());
        Fabrica.fabricaEscenario();
        SistemaDeReserva sistemaD1 = Fabrica.getSistemaDeReserva();
        sistemaD1.reservaAsientos(funcion, numeroDeFila, numerosDeAsientos, cliente);        
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //         java.awt.EventQueue.invokeLater(new Runnable() {
        //                 public void run() {
        //                     new ClienteGUI().setVisible(true);
        //                 }
        //             });
    }

    private JButton jbGuardar;
    private JButton jbOtro;
    private JButton jbCancelar;
    private JLabel jlTelefono;
    private JLabel jlEmail;
    private JLabel jlNombre;
    private JTextField jtfTelefono;
    private JTextField jtfEmail;
    private JTextField jtfNombre;
    private JTextArea jtaFuncion;    
    private JPanel jpDatos;
    private JPanel jpControles;
    // End of variables declaration                   
}
